services:
  backend:
    build:
      context: ./backend
      dockerfile: dockerfile.prod
    ports:
      - "8000:8000"
    environment:
      - DEV_MODE=development
      # - DEV_MODE=production
    env_file:
      - ./backend/.env.prod

  frontend:
    build:
      context: ./frontend
      dockerfile: dockerfile.prod
    # ports:
    #   - "3000:3000"
    environment:
      - NODE_ENV=development
      # - NODE_ENV=production

  nginx:
    image: nginx:latest
    ports:
      - "80:80"
      - "443:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - backend
      - frontend
